package db

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
)

// structureSnapshotFile is the name of the schema snapshot inside db/.
const structureSnapshotFile = "structure.sql"

// dbDir is the absolute path to the repository's db/ directory.
//
// It is read from disk rather than //go:embed'd on purpose: nothing in
// production uses it, and embedding it shipped a schema snapshot inside every
// release binary. Only tests and the dev-only `db-init` command read it.
var dbDir = resolveDBDir()

// resolveDBDir locates db/ in two steps, because neither one alone is reliable.
//
// The compile-time source path is preferred: it holds up no matter what the
// process working directory is. But runtime.Caller reports the path as recorded
// when the package was compiled, and a -trimpath build rewrites that to a
// module-relative path such as kids-checkin/internal/db/schema.go. Joining
// ".." onto it yields kids-checkin/db, which only resolves if the working
// directory happens to be the module root -- so under -trimpath the preferred
// candidate silently points at nothing.
//
// That is why the candidate is verified before it is trusted, and why a walk up
// from the working directory backs it up. Dropping the verification (or the
// walk) reintroduces the failure the verification exists to catch: db/structure.sql
// not found, in every package that builds a test database.
func resolveDBDir() string {
	if _, thisFile, _, ok := runtime.Caller(0); ok {
		candidate := filepath.Clean(filepath.Join(filepath.Dir(thisFile), "..", "..", "db"))
		if snapshotExists(candidate) {
			return candidate
		}
	}
	if wd, err := os.Getwd(); err == nil {
		if dir, ok := findDBDir(wd); ok {
			return dir
		}
	}
	// Nothing found. Return the compile-time-shaped guess so the resulting
	// error names a plausible path instead of an empty string.
	return "db"
}

// findDBDir walks up from start, returning the first ancestor directory that
// holds a db/ directory containing the schema snapshot. This is what resolves
// the path in a -trimpath build, where the working directory is the only
// trustworthy anchor left.
//
// It matches on the snapshot file rather than on a directory named db, so a
// stray or empty db/ higher up the tree cannot shadow the real one.
func findDBDir(start string) (string, bool) {
	for dir := start; ; {
		candidate := filepath.Join(dir, "db")
		if snapshotExists(candidate) {
			return candidate, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

func snapshotExists(dir string) bool {
	info, err := os.Stat(filepath.Join(dir, structureSnapshotFile))
	return err == nil && !info.IsDir()
}

// StructureSQL returns db/structure.sql, the schema snapshot generated by
// `make db-migrate` from the migrations in db/migrations.
func StructureSQL() (string, error) {
	path := filepath.Join(dbDir, structureSnapshotFile)
	contents, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read schema snapshot %s: %w", path, err)
	}
	return string(contents), nil
}
